### PR TITLE
Support isort >= 5

### PR DESCRIPTION
**Pull request by mom1**
Hi. I hope this will be usefull.

### CODE REVIEW

**Comment by rwols** [comment]
ping @paradoxxxzero

**Comment by timbedard** [comment]
Any word on reviewing and merging this PR?

**Comment by karolyi** [comment]
+1

**Comment by agrinh** [comment]
+1

**Comment by agrinh** [comment]
Would be great to get this in

**Comment by karolyi** [comment]
@paradoxxxzero, are you waiting for something?

**Comment by paradoxxxzero** [comment]
So sorry about the delay, I've been quite busy recently.
If someone want to take maintenership just ask :)

**Comment by agrinh** [comment]
@paradoxxxzero Thanks for merging! Any idea if this could be absorbed into https://github.com/palantir/python-language-server? It seems like they already host plenty of plugins there, both isort and mypy frankly seem like pretty odd exclusions.

**Pull request merged**
